[[redirects]]
  from = "https://create.agenly.site/*"
  to = "https://laughing-perlman-57b2e6.netlify.com/:splat"
  status = 200
  force = true

  [[redirects]]
    from = "https://app.agenly.site/*"
    to = "https://laughing-perlman-57b2e6.netlify.com/:splat"
    status = 200
    force = true

    [[redirects]]
    from = "https://agenly.site/sites/*"
    to = "https://laughing-perlman-57b2e6.netlify.com/sites/:splat"
    status = 200
    force = true